---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      provider: virtualbox
      customize:
        memory: 1024

suites:
  - name: default
    run_list:
      - recipe[base::default]
      - recipe[chef-solo-search]
    attributes:
    data_bags_path: "test/integration/data_bags"
